"""Service layer for the demo: the frozen Phase 8 final system plus deterministic explanations.

System (frozen, see docs/final_evaluation.md):
  questions -> MiniLM -> Phase 3 MLP head -> base probability
            -> spaCy-free constraint features -> Phase 6 meta-model -> final probability -> global threshold (0.35)
  pair embedding -> frozen Phase 4 centroids -> cluster (context only: Phase 7 rejected per-cluster thresholds)

Explanations are deterministic and model-based. Nothing is generated by a language model:
  - extracted items per question (numbers, dates, capitalised entities, negation, question word, content words)
  - mismatch signals, read from the same features the model uses
  - "what-if" effects: the meta-model re-scored as if one constraint group (numbers, dates, entities,
    negation, question word) had MATCHED across the two questions. This is a counterfactual on the model,
    not a claim about causes in the text. Scope/specificity is reported as a signal but has no what-if:
    "no content difference" is not a coherent state for two different questions.
"""
from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from pathlib import Path

import numpy as np
import pandas as pd

from src.features.constraints import FEATURE_GROUPS, WH_WORDS, annotate
from src.models.sentence_encoder import clean
from src.utils.data import PROJECT_ROOT

ART = PROJECT_ROOT / "artifacts"
BORDERLINE = 0.05  # |p - tau| below this is reported as a borderline decision

GROUP_LABELS = {"number": "numbers", "date_heuristic": "dates", "entity_heuristic": "named entities",
                "negation": "negation", "intent_word": "question word", "specificity": "scope / specificity"}


@dataclass
class MatchResult:
    question_a: str
    question_b: str
    final_probability: float
    decision: bool
    global_threshold: float
    borderline: bool
    base_probability: float
    base_threshold: float
    base_decision: bool
    semantic_similarity: float
    cluster_id: int
    cluster_name: str
    cluster_margin: float
    near_cluster_boundary: bool
    cluster_threshold_applied: bool
    cluster_threshold_note: str
    extracted: dict = field(default_factory=dict)
    signals: list = field(default_factory=list)
    what_if: list = field(default_factory=list)
    rationale: list = field(default_factory=list)

    def to_dict(self) -> dict:
        return asdict(self)


class DuplicateMatcher:
    def __init__(self, device: str = "cpu"):
        from src.calibration.thresholds import ThresholdPolicy
        from src.clustering.core import CentroidModel
        from src.models.predictors import MetaPredictor
        self.predictor = MetaPredictor(ART / "phase6" / "meta_model.joblib", device=device)
        final = ThresholdPolicy.load(ART / "phase7" / "frozen_policy_final.json")
        base = ThresholdPolicy.load(ART / "phase7" / "frozen_policy_baseline.json")
        assert final.mode == "global", "the frozen final system uses a global threshold"
        self.tau, self.base_tau = final.global_threshold, base.global_threshold
        self.clusters = CentroidModel.load(ART / "phase4" / "cluster_model")
        names = json.loads((ART / "phase4" / "cluster_names.json").read_text())
        self.cluster_names = {int(k): v["name"] for k, v in names.items() if not k.startswith("_")}
        self.groups = list(self.predictor.meta.variant.groups)

    # ------------------------------------------------------------------ core
    def score_frame(self, feats: pd.DataFrame) -> np.ndarray:
        return self.predictor.meta.predict_proba(feats)

    def match(self, question_a: str, question_b: str) -> MatchResult:
        from src.clustering.pairs import centroid_geometry, pair_embedding
        qa, qb = clean(question_a), clean(question_b)
        if not qa or not qb:
            raise ValueError("Both questions must be non-empty.")
        feats = self.predictor.features([qa], [qb])
        final_p = float(self.score_frame(feats)[0])
        base_p = float(feats["base_prob"].iloc[0])
        u, v = self.predictor.base.embed([qa]), self.predictor.base.embed([qb])
        geo = centroid_geometry(pair_embedding(u, v), self.clusters)
        cid = int(geo["cluster"][0])
        margin = float(geo["margin"][0])

        ann_a, ann_b = annotate(qa), annotate(qb)
        extracted = {"question_a": self._items(ann_a), "question_b": self._items(ann_b)}
        signals = self._signals(feats.iloc[0], ann_a, ann_b)
        what_if = self._what_if(feats, final_p)
        result = MatchResult(
            question_a=qa, question_b=qb, final_probability=final_p, decision=final_p >= self.tau,
            global_threshold=self.tau, borderline=abs(final_p - self.tau) < BORDERLINE,
            base_probability=base_p, base_threshold=self.base_tau, base_decision=base_p >= self.base_tau,
            semantic_similarity=float(feats["cosine"].iloc[0]), cluster_id=cid,
            cluster_name=self.cluster_names.get(cid, f"cluster {cid}"), cluster_margin=margin,
            near_cluster_boundary=margin < 0.016,  # bottom quartile of validation pair margins (Phase 5)
            cluster_threshold_applied=False,
            cluster_threshold_note=("Not applied. Phase 7 found per-cluster thresholds lowered macro-cluster F1 out of sample, "
                                    "so the frozen system uses one global threshold for every cluster."),
            extracted=extracted, signals=signals, what_if=what_if)
        result.rationale = self._rationale(result)
        return result

    # ------------------------------------------------------------------ explanation helpers
    @staticmethod
    def _items(ann: dict) -> dict:
        return {"numbers": sorted(ann["numbers"]), "dates": sorted(ann["dates"]), "entities": sorted(ann["ents_heur"]),
                "has_negation": ann["negation"] > 0, "question_word": ann["wh"] or None,
                "content_words": sorted(ann["content"])}

    @staticmethod
    def _unmatched(a: set, b: set, b_norm: str) -> list:
        return sorted(x for x in a if x not in b and f" {x} " not in b_norm)

    def _signals(self, f: pd.Series, a: dict, b: dict) -> list:
        """Mismatch signals in plain words, derived from the model's own features."""
        out = []
        for key, label, items_a, items_b in (("num", "Numbers", a["numbers"], b["numbers"]),
                                             ("dateh", "Dates", a["dates"], b["dates"]),
                                             ("enth", "Named entities", a["ents_heur"], b["ents_heur"])):
            only_a = self._unmatched(items_a, items_b, b["norm"])
            only_b = self._unmatched(items_b, items_a, a["norm"])
            if f[f"{key}_mismatch"]:
                out.append({"type": f"{label.lower()} mismatch", "detail": f"{label} differ: {only_a or '-'} vs {only_b or '-'}"})
            elif f[f"{key}_one_sided"]:
                side, items = ("A", only_a) if only_a else ("B", only_b)
                out.append({"type": f"{label.lower()} only in one question",
                            "detail": f"{label} only in question {side}: {items}"})
        if f["neg_xor"]:
            neg = "A" if a["negation"] > 0 else "B"
            out.append({"type": "negation mismatch", "detail": f"Only question {neg} is negated"})
        if f["wh_mismatch"]:
            out.append({"type": "question word differs", "detail": f"'{a['wh']}' vs '{b['wh']}'"})
        only_a = sorted(a["content"] - b["content"] - WH_WORDS)
        only_b = sorted(b["content"] - a["content"] - WH_WORDS)
        if f["content_subset"]:
            broader = "A" if not only_a else "B"
            extra = only_b if broader == "A" else only_a
            out.append({"type": "broader / narrower",
                        "detail": f"Question {broader} is broader; the other adds {extra}"})
        elif only_a or only_b:
            out.append({"type": "different content words", "detail": f"only in A: {only_a[:6]}; only in B: {only_b[:6]}"})
        return out

    # Coherent "no difference" values per group: items are kept, but treated as MATCHING on both sides.
    # Specificity is excluded: "identical content words" is impossible for two different questions.
    _WHAT_IF_GROUPS = ("number", "date_heuristic", "entity_heuristic", "negation", "intent_word")

    def _what_if(self, feats: pd.DataFrame, final_p: float) -> list:
        """Score change if one constraint group had shown no difference (counterfactual on the model)."""
        out = []
        for g in self.groups:
            if g not in self._WHAT_IF_GROUPS:
                continue
            cols = FEATURE_GROUPS[g]
            diff_cols = [c for c in cols if not c.endswith(("_any", "_both"))]
            if not feats[diff_cols].to_numpy().any():
                continue  # this group shows no difference: nothing to neutralise
            neutral = feats.copy()
            neutral[diff_cols] = 0.0
            for c in cols:
                if c.endswith("_both"):
                    neutral[c] = neutral[c.replace("_both", "_any")]  # as if the items appeared in both questions
            p = float(self.score_frame(neutral)[0])
            out.append({"group": GROUP_LABELS.get(g, g), "probability_if_no_difference": p, "effect": final_p - p})
        return sorted(out, key=lambda d: d["effect"])

    def _rationale(self, r: MatchResult) -> list:
        lines = []
        sim_word = "very similar" if r.semantic_similarity >= 0.85 else "similar" if r.semantic_similarity >= 0.6 else "not very similar"
        lines.append(f"The sentence embeddings are {sim_word} (cosine {r.semantic_similarity:.2f}); "
                     f"the semantic model alone gives {r.base_probability:.2f} "
                     f"({'duplicate' if r.base_decision else 'not duplicate'} at its threshold {r.base_threshold:.2f}).")
        if r.signals:
            lines.append("Consistency checks found: " + "; ".join(s["detail"] for s in r.signals) + ".")
        else:
            lines.append("Consistency checks found no number, date, entity, negation or scope difference.")
        strong = [w for w in r.what_if if abs(w["effect"]) >= 0.05]
        for w in strong[:3]:
            direction = "lowered" if w["effect"] < 0 else "raised"
            lines.append(f"The {w['group']} difference {direction} the score: if the {w['group']} matched, the model would give "
                         f"{w['probability_if_no_difference']:.2f} instead of {r.final_probability:.2f}.")
        verdict = "duplicate" if r.decision else "not a duplicate"
        lines.append(f"Final probability {r.final_probability:.2f} {'≥' if r.decision else '<'} global threshold {r.global_threshold:.2f}"
                     f" → {verdict}{' (borderline)' if r.borderline else ''}.")
        if r.near_cluster_boundary:
            lines.append("The pair sits near a boundary between discovered query groups; the group label is a soft context hint only.")
        return lines
